# review-epubmaker向けの設定ファイルの例。
# yamlファイルをReVIEWファイルのある場所に置き、
# 「review-epubmaker yamlファイル」を実行すると、<bookname>.epubファイルが
# 生成されます。
# このファイルはUTF-8エンコーディングで記述してください。

# ブック名(ファイル名になるもの。ASCII範囲の文字を使用)
bookname: book
# 書名
booktitle: 徹底解剖「G1GC」実装編
# 著者
aut: 中村成洋
prt: 達人出版会
date: 2013-05-28
rights: |
  (C) 2012-2013 Narihiro Nakamura
description: 本書はOpenJDK7のG1GCの実装と、それに関連する技術を解説します。
# 以下はオプション
# prt: 出版社
# asn: Associated name
# ant: Bibliographic antecedent
# clb: 貢献者
# edt: 編集者
# dsr: デザイナ
# ill: イラストレータ
# pht: 撮影者
# trl: 翻訳者
# date: 刊行日
# rights: 権利表記
# description: ブックの説明
#
# coverfile: カバーページのbody要素内に挿入する内容を記述したファイル名
# coverimage: 表紙用画像ファイル
# 固有IDに使用するドメイン
coverfile: _cover.html
coverimage: cover.jpg
urnid: http://tatsu-zine.com/books/g1gc-impl/
# CSSファイル (yamlファイルおよびReVIEWファイルを置いたディレクトリにあること)
stylesheet: stylesheet.css
##texstyle: review
texstyle: tatsumacro
texdocumentclass: ["jsbook", "oneside,14pt"]
# 目次として抽出するレベル
toclevel: 2
# セクション番号を表示するレベル
secnolevel: 3
# review-compileに渡すパラメータ
params: --stylesheet=stylesheet.css --subdirmode
# 目次生成用？
mytoc: true
# 奥付用
pubhistory: |
  2012年9月14日 発行
  2013年5月28日 達人出版会版 v1.0.0 発行
colophon: true
# debug
# debug: false
debug: true

